---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: systems
  sources:
  - repoURL: 194271732102.dkr.ecr.eu-west-1.amazonaws.com/charts
    chart: crossplane-resources
    targetRevision: 0.0.0+125.1
    helm:
      valueFiles:
      - "$values/clusters/giuliodev-a/eu-west-1/values/systems/crossplane-resources/values.yaml"
  - repoURL: git@github.com:Chillibean/argocd-applications.git
    targetRevision: improvement/TEC-141-improve-resource-usage
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: systems
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - preserveResourcesOnDeletion=false
  revisionHistoryLimit: 1
