---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: systems
  sources:
  - repoURL: git@github.com:Chillibean/argocd-applications.git
    targetRevision: improvement/TEC-141-improve-resource-usage
    path: clusters/giuliodev-a/eu-west-1/values/systems/elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: app-systems
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - preserveResourcesOnDeletion=false
  revisionHistoryLimit: 1
