---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: "systems"
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: "kube-prometheus-stack"
      targetRevision: 46.4.2
      helm:
        valueFiles:
          - $values/clusters/giuliodev-a/values/systems/kube-prometheus-stack/values.yaml
    - repoURL: git@github.com:Chillibean/argocd-applications.git
      targetRevision: improvement/TEC-141-improve-resource-usage
      ref: values
    - repoURL: git@github.com:Chillibean/argocd-applications.git
      targetRevision: improvement/TEC-141-improve-resource-usage
      path: clusters/giuliodev-a/eu-west-1/values/systems/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: "systems"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - preserveResourcesOnDeletion=false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/validation
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .spec.endpoints[]?.relabelings[]?.action
  revisionHistoryLimit: 1
