---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: systems
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 4.0.0
    helm:
      valueFiles:
      - "$values/clusters/giuliodev-a/eu-west-1/values/systems/prometheus-operator-crds/values.yaml"
  - repoURL: git@github.com:Chillibean/argocd-applications.git
    targetRevision: improvement/TEC-141-improve-resource-usage
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: systems
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - preserveResourcesOnDeletion=false
    - ServerSideApply=true
  revisionHistoryLimit: 1
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - "/metadata/annotations"
    - "/metadata/labels"
    - "/spec/validation"
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - "/webhooks"
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - "/webhooks"
  - group: monitoring.coreos.com
    kind: ServiceMonitor
    jqPathExpressions:
    - ".spec.endpoints[]?.relabelings[]?.action"
