---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: systems
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-adapter
    targetRevision: 4.2.0
    helm:
      valueFiles:
      - "$values/clusters/giuliodev-a/eu-west-1/values/systems/prometheus-adapter/values.yaml"
  - repoURL: git@github.com:Chillibean/argocd-applications.git
    targetRevision: improvement/TEC-141-improve-resource-usage
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: systems
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - preserveResourcesOnDeletion=false
  revisionHistoryLimit: 1
